{% set name = "pythonji-2" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythonji_2-{{ version }}.tar.gz
  sha256: f8ddf28712941e8401a29885a9fab2c0cbeeebe0ceb57f21cedfecfdfdb5ee08

build:
  entry_points:
    - pythonji = pythonji.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - emoji

test:
  imports:
    - pythonji
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pavelzw/pythonji-2
  summary: 🐍 - Write Python with Emojis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
